### ISSUE TITLE
textが設定できません

### ISSUE THREAD

**Issue by isozaki** [maki-tetsu/atna#4]
ParticipantObjectNameとParticipantObjectQueryはテキストの指定が必要ですが、現在できません

**Comment by maki-tetsu** [comment]
機能がありませんでした。対応します。

**Comment by maki-tetsu** [comment]
現状各シンボルや文字列をキーとした値の設定には、Hash か Array しか設定できません。ここに、キーが文字列(Element)の場合に限り、文字列を直接指定することで、text として設定するようにします。
